#! /usr/bin/env sh

while getopts "hpf:" opt; do
  case $opt in
    p)
      MARKDOWN="| markdown"
      ;;
    f)
      echo "-f using file: $OPTARG" > /dev/null
      PKG_FILE=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$PKG_FILE" ]; then
    if [ -f "$1" ]; then
        PKG_FILE="$1"
    else
        echo "Package file not set" >&2
        exit 1
    fi
fi

if [ ! -f $PKG_FILE ]; then
    echo "Package file not found" >&2
    exit 1
fi

cd $PWD
PKG_INFO=$(cat $PKG_FILE)
if [ -f $PKG_FILE.md ]; then
        rm $PKG_FILE.md
fi
PKGFILEBIN=$(cat $PKG_FILE | grep 'Package:' | sed -e 's/^[ \t]*//')
HONE="============="
if [ ! -z "$MARKDOWN" ]; then
    printf "%b\n" "\n<div id=\"header\">\n"
fi
[ ! ! -z "$PKGFILEBIN" ] && printf "%b\n" "$PKGFILEBIN \n$HONE \n" | tee $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
PKGFILESRC=$(cat $PKG_FILE | grep 'Source:' | sed -e 's/^[ \t]*//')
HTWO="-------------"
[ ! -z "$PKGFILESRC" ] && printf "%b\n" "$PKGFILESRC \n$HTWO \n" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
if [ ! -z "$MARKDOWN" ]; then
    printf "%b\n" "\n</div>\n"
    printf "%b\n" "\n<div id=\"content\">\n"
fi
PKGFILEVER=$(echo -n "###" && cat $PKG_FILE | grep 'Version:' | sed -e 's/^[ \t]*//')
PKGFILEMAN=$(echo -n "####" && cat $PKG_FILE | grep 'Maintainer:' | sed -e 's/^[ \t]*//')
PKGFILEDEP=$(cat $PKG_FILE | grep 'Build-Depends:' | sed -e 's/^[ \t]*//' | sed -e 's/Build-Depends:/###Build-Depends:\n  */')
PKGFILEREC=$(cat $PKG_FILE | grep 'Vcs-Browser:' | sed -e 's/^[ \t]*//' | sed -e 's/Vcs-Browser:/###Vcs-Browser:\n  */')
[ ! -z "$PKGFILEVER" ] && printf "%b\n" "$PKGFILEVER" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILEMAN" ] && printf "%b\n" "$PKGFILEMAN" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILEDEP" ] && printf "%b\n" "$PKGFILEDEP" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILEREC" ] && printf "%b\n" "$PKGFILEREC" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
if [ ! -z "$MARKDOWN" ]; then
    printf "%b\n" "\n</div>\n"
    printf "%b\n" "\n<div id=\"sidebar\">\n"
fi
PKGFILEPRV=$(cat $PKG_FILE | grep 'Provides:' | sed -e 's/^[ \t]*//' | sed -e 's/Provides:/###Provides:\n  */')
PKGFILESEC=$(echo -n "####" && cat $PKG_FILE | grep 'Architecture:' | sed -e 's/^[ \t]*//')
PKGFILEPRI=$(echo -n "####" && cat $PKG_FILE | grep 'Binary:' | sed -e 's/^[ \t]*//')
PKGFILESIZ=$(echo -n "####" && cat $PKG_FILE | grep 'Vcs-Git:' | sed -e 's/^[ \t]*//')
PKG_URL=$(cat $PKG_FILE | grep 'Homepage:' | sed -e 's/Homepage:/ /' | sed -e 's/^[ \t]*//') #)
PKGFILEURL=$(cat $PKG_FILE | grep 'Homepage:' | sed -e 's/^[ \t]*//' | sed -e 's/Homepage:/Homepage:[/' | tr "\n" " " && echo "]($PKG_URL)")
[ ! -z "$PKGFILEURL" ] && printf "%b\n" "$PKGFILEURL" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILEPRV" ] && printf "%b\n" "$PKGFILEPRV" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILESEC" ] && printf "%b\n" "$PKGFILESEC" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILESIZ" ] && printf "%b\n" "$PKGFILESIZ" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)
[ ! -z "$PKGFILEPRI" ] && printf "%b\n" "$PKGFILEPRI" | tee -a $PKG_FILE.md | ( [ "${MARKDOWN}" ] && markdown)

if [ ! -z "$MARKDOWN" ]; then
    printf "%b\n" "\n</div>\n"
fi

if [ -z "$MARKDOWN" ]; then
     cat $PKG_FILE.md
fi
