Document: scpage
Title: Debian scpage Manual
Author: <insert document author here>
Abstract: This manual describes what scpage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scpage/scpage.sgml.gz

Format: postscript
Files: /usr/share/doc/scpage/scpage.ps.gz

Format: text
Files: /usr/share/doc/scpage/scpage.text.gz

Format: HTML
Index: /usr/share/doc/scpage/html/index.html
Files: /usr/share/doc/scpage/html/*.html
